"""Initial migration

Revision ID: 40df19df7bac
Revises: 
Create Date: 2025-12-15 16:42:46.809138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40df19df7bac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('trade_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('broker_name', sa.String(length=100), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('open_time', sa.DateTime(), nullable=True),
    sa.Column('close_time', sa.DateTime(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('swap', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['trade_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade')
    op.drop_table('trade_account')
    op.drop_table('user')
    # ### end Alembic commands ###
