"""Initial migration

Revision ID: 6a69dd417203
Revises: 40df19df7bac
Create Date: 2025-12-16 16:05:36.697663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a69dd417203'
down_revision = '40df19df7bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_trade_timestamp'), ['timestamp'], unique=False)
        batch_op.create_foreign_key('fk_trade_user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('close_time')
        batch_op.drop_column('ticket')
        batch_op.drop_column('type')
        batch_op.drop_column('swap')
        batch_op.drop_column('open_time')
        batch_op.drop_column('size')
        batch_op.drop_column('close_price')
        batch_op.drop_column('open_price')
        batch_op.drop_column('commission')

    with op.batch_alter_table('trade_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('account_number')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_demo')
        batch_op.drop_column('last_updated')
        batch_op.drop_column('broker_name')
        batch_op.drop_column('account_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=64),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.drop_column('is_admin')
        batch_op.drop_column('created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('trade_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('broker_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_demo', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('balance')
        batch_op.drop_column('name')

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('open_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('close_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('size', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('open_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('swap', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('ticket', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('close_time', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('fk_trade_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_trade_timestamp'))
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('price')
        batch_op.drop_column('volume')
    # ### end Alembic commands ###